# Generated by Django 3.0.3 on 2020-03-10 01:14

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompositeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_plot', django_matplotlib.fields.MatplotlibFigureField()),
                ('sine_plot', django_matplotlib.fields.MatplotlibFigureField()),
                ('imshow_demo', django_matplotlib.fields.MatplotlibFigureField()),
                ('with_args', django_matplotlib.fields.MatplotlibFigureField()),
                ('countour_plot', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
