# Generated by Django 3.0.3 on 2020-03-10 01:27

from django.db import migrations, models
import django_matplotlib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('processingImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_plot', django_matplotlib.fields.MatplotlibFigureField()),
            ],
        ),
    ]
